name: 'Config Entity Example'
type: module
description: 'Demonstrates how to create a config entity type.'
package: Example modules
core: 8.x
core_version_requirement: ^8 || ^9
dependencies:
  - examples:examples

# Information added by Drupal.org packaging script on 2020-05-27
version: '3.0.1'
project: 'examples'
datestamp: 1590583592
