name: 'Configuration Manager'
type: module
description: 'Allows administrators to import and export configuration changes.'
package: Core
# version: VERSION
core: 8.x
configure: config.sync

# Information added by Drupal.org packaging script on 2020-06-03
version: '8.9.0'
project: 'drupal'
datestamp: 1591204166
