name: Testing site config
type: profile
description: 'Minimal profile for testing with default site config.'
# version: VERSION
core: 8.x
hidden: true

# Information added by Drupal.org packaging script on 2020-06-03
version: '8.9.0'
project: 'drupal'
datestamp: 1591204166
